import React from 'react'
import "./globals.css";

import { Item, Bid, Model, SoldItem } from '../model'

function ToAuctionItems({model, andRefreshDisplay, callbacks}: {model: Model; andRefreshDisplay: () => void; callbacks: any}) {
    const [itemsAvailable, changeItemsAvailable] = React.useState(model.itemsToAuction)
    
    callbacks.redrawToAuction = changeItemsAvailable
    //React.useEffect(() => {changeItemsAvailable([...model.itemsToAuction]);}, [model.itemsToAuction]); // this line was generated by chatgpts

    // CONTROLLER
    function addItem() {
        const itemName = (document.getElementById("new-item-name") as HTMLInputElement).value
        const itemDescription = (document.getElementById("new-item-description") as HTMLInputElement).value
        const initialPrice = +(document.getElementById("new-item-price") as HTMLInputElement).value
        const newItem = new Item(Date.now().toString(), itemName, itemDescription, initialPrice)

        if (!model.auctionStarted && !Number.isNaN(newItem.initialPrice)){
          model.addItemToAuction(newItem)
        }
        if (!model.auctionStarted){
          model.soldItems = []
          callbacks.redrawSoldItems([...model.soldItems])
          model.auctionEnded = false
        }

        callbacks.redrawToAuction([...model.itemsToAuction])
        andRefreshDisplay()
    }

    return (
        <div>
          <h1>Items to auction ({model.itemsToAuction.length})</h1>
          <p><b>Name: </b><input id="new-item-name" placeholder="Item name"></input></p>
          <p><b>Initial bid: </b><input id="new-item-price" placeholder="Initial bid price"></input></p>
          <p><b>Description: </b><input id="new-item-description" placeholder="Item description"></input></p>
          <div className="spacer"></div>
          <button data-testid="add-item-button" onClick={() => {addItem()}}>Add Item</button>
          <div className="spacer"></div>
          <ul>
            {itemsAvailable.map((item: Item) => (
              <li key={item.id}>{item.name} - {item.description} - ${item.initialPrice}</li>
            ))}
          </ul>
        </div>
    )
}

function CurrentItem({model, andRefreshDisplay, callbacks}: {model: Model; andRefreshDisplay: () => void; callbacks: any}) {
    

    // CONTROLLER
    function nextItem() {
        if(!model.currentItem && model.itemsToAuction.length > 0){
          if(!model.auctionStarted){
            model.auctionStarted = true;
          }
          model.currentItem = model.itemsToAuction[0]
          model.itemsToAuction = model.itemsToAuction.slice(1, model.itemsToAuction.length)
        }
        
        callbacks.redrawBids([...model.currentBids])
        callbacks.redrawToAuction([...model.itemsToAuction])
        andRefreshDisplay()
    }

    // CONTROLLER
    function sellItem() {
      if (model.currentItem && model.currentBids.length > 0){
        const lastBid: Bid = model.currentBids[model.currentBids.length-1]
        
        model.addSoldItem(new SoldItem(model.currentItem, lastBid))
        model.soldItems = [...model.soldItems]
        
        model.totalNetSales += lastBid.amount-model.currentItem.initialPrice

        model.currentItem = undefined
        model.currentBids = []
      }
      
      callbacks.redrawBids([...model.currentBids])
      callbacks.redrawSoldItems([...model.soldItems])
      andRefreshDisplay()
    }

    return (
        <div>
          <h1>Current Item</h1>
          <p>
            {model.currentItem && <b>{model.currentItem.name} - {model.currentItem.description} - ${model.currentItem.initialPrice}</b>}
            {!model.auctionStarted && !model.auctionEnded && <b>Auction has not started.</b>}
            {!model.auctionStarted && model.auctionEnded && <b>Auction has ended.</b>}
            {model.auctionStarted && !model.currentItem && <b>No item selected.</b>}
          </p>
          <div className="spacer"></div>
          <p><button data-testid="auction-next-item-button" onClick={() => {nextItem()}}>Auction Next Item</button></p>
          <p><button data-testid="sell-item-button" onClick={() => {sellItem()}}>Sell Item</button></p>
        </div>
    )
}

function Bidding({model, andRefreshDisplay, callbacks}: {model: Model; andRefreshDisplay: () => void; callbacks: any}) {
  const [bids, changeBids] = React.useState(model.currentBids)

  //React.useEffect(() => {changeBids([...model.currentBids]);}, [model.currentBids]); // this line was generated by chatgpt

  callbacks.redrawBids = changeBids

  function addBid() {
        const bidderName = (document.getElementById("bidder-name") as HTMLInputElement).value
        const bidAmount = +(document.getElementById("bid-amount") as HTMLInputElement).value
        
        if (model.currentItem && (
              (model.currentBids.length==0 && bidAmount >= model.currentItem.initialPrice) 
              || (bidAmount >= model.currentItem.initialPrice && bidAmount > model.currentBids[model.currentBids.length-1].amount)
            )){
          const newBid = new Bid(Date.now().toString(), bidderName, bidAmount)

          model.createNewBid(newBid)

          callbacks.redrawBids([...model.currentBids])
          andRefreshDisplay()
        }
    }

    return (
        <div>
           <h1>Bids</h1>
           <div className="spacer"></div>
           <p><b>Name: </b><input id="bidder-name" placeholder="Bidder name"></input></p>
           <p><b>Amount: </b><input id="bid-amount" placeholder="Bid amount"></input></p>
           <button data-testid="place-bid-button" onClick={() => {addBid()}}>Place Bid</button>
           <div className="spacer"></div>
        <ul>
          {bids.map((bid: Bid) => (
            <li key={bid.id}>{bid.name} ${bid.amount}</li>
          ))}
        </ul>
        </div>
    )
}

function SoldItems({model, andRefreshDisplay, callbacks}: {model: Model; andRefreshDisplay: () => void; callbacks: any}) {
  const [soldItems, changeItems] = React.useState(model.soldItems)

  //React.useEffect(() => {changeItems([...model.soldItems]);}, [model.soldItems]); // this line was generated by chatgpt

  callbacks.redrawSoldItems = changeItems

    return ( 
        <ul>
          {soldItems.map((item: SoldItem) => (
            <li key={item.item.id}>{item.item.name} sold to {item.finalBid.name} for ${item.finalBid.amount}</li>
          ))}
        </ul>
    )
}

function CloseAuction({model, andRefreshDisplay, callbacks}: {model: Model; andRefreshDisplay: () => void; callbacks: any}) {
    const [bids, changeBids] = React.useState(model.currentBids)

    // CONTROLLER
    function close() {
      
      if (model.itemsToAuction.length == 0 && model.soldItems.length > 0 && model.currentItem == undefined){
        model.auctionStarted = false
        model.auctionEnded = true
      }

      callbacks.redrawToAuction([...model.itemsToAuction])
      callbacks.redrawBids([...model.currentBids])
      callbacks.redrawSoldItems([...model.soldItems])
      andRefreshDisplay()
    }

    return (
      <button data-testid="close-auction-button" onClick={() => {close()}}>Close auction</button>
    )
}


export { ToAuctionItems, CurrentItem as AuctionNextItem, Bidding, SoldItems, CloseAuction }